# Generated by Django 2.2.5 on 2020-03-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('article', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('answer', models.CharField(max_length=2)),
                ('option_a', models.CharField(max_length=512)),
                ('option_b', models.CharField(max_length=512)),
                ('option_c', models.CharField(max_length=512)),
                ('option_d', models.CharField(max_length=512)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReadingTest.Reading')),
            ],
        ),
    ]
