# Generated by Django 2.2.5 on 2020-03-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingTest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Q_A',
        ),
    ]
